# ./docker-compose.yml

version: '3'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ------
      MYSQL_DATABASE: ------
      MYSQL_USER: -----
      MYSQL_PASSWORD: -----
    ports:
      - "9906:3306"
  web:
    image: php:7-apache
    container_name: php_web
    depends_on:
      - db
    volumes:
      - ./public_html/:/var/www/html/
    ports:
      - "8100:80"
    stdin_open: true
    tty: true
